name: deploy-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  tests_deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js to specific version LTS and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies for project
        run: npm install

      - name: Typecheck TypeScript to App
        run: npm run typecheck

      - name: Deploy PR (main) for new Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          default-branch: main
          changelog-types: '[
            {"type":"feat","section":"ğŸš€ Features","hidden":false},
            {"type":"fix","section":"ğŸ› Bug Fixes","hidden":false},
            {"type":"chore","section":"ğŸ§¹ Chores","hidden":false},
            {"type":"revert","section":"âª Reverts","hidden":false},
            {"type":"ci","section":"ğŸ”§ Continuous Integration","hidden":false},
            {"type":"docs","section":"ğŸ“š Documentation","hidden":false},
            {"type":"style","section":"ğŸ’„ Styling","hidden":false},
            {"type":"refactor","section":"â™»ï¸ Refactoring","hidden":false},
            {"type":"test","section":"ğŸ§ª Tests","hidden":false},
            {"type":"perf","section":"â± Performance Improvements","hidden":false},
            {"type":"build","section":"ğŸ— Build System","hidden":false}
          ]'
          token: ${{ secrets.PAT }}
